### ISSUE TITLE
Attempting to view shaders causes a crash

### ISSUE THREAD

**Issue by TheStolenBattenberg** [TheStolenBattenberg/MA-Engine#7]
Open MAE.gmx, press the 3 key, be awarded with a crash. MAE does not throw any errors.

**Comment by falki147** [comment]
Due to me changing the system to pass pointers instead of indices I wasn't able to update the `MAE_ShaderSet` function properly (when passed a value of less than 0 the shader would be reset) I fixed it by adding a new function called `MAE_ShaderReset`
